// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerDataAggregation.Persistence;

#nullable disable

namespace ServerDataAggregation.Persistence.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20220411002523_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerDataAggregation.Persistence.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<int>("FailedQueryAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_query_attempts");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<DateTime?>("LastQuery")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_query");

                    b.Property<DateTime?>("LastQuerySuccess")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_query_success");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("ModificationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification_code");

                    b.Property<DateTime?>("NextQuery")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_query");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parameters");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("QueryInterval")
                        .HasColumnType("integer")
                        .HasColumnName("query_interval");

                    b.Property<int>("QueryResult")
                        .HasColumnType("integer")
                        .HasColumnName("query_result");

                    b.HasKey("ServerId");

                    b.ToTable("server");
                });

            modelBuilder.Entity("ServerDataAggregation.Persistence.Models.ServerSnapshot", b =>
                {
                    b.Property<int>("ServerSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("server_snapshot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerSnapshotId"));

                    b.Property<int>("ServerId")
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    b.HasKey("ServerSnapshotId");

                    b.ToTable("server_snapshot");
                });

            modelBuilder.Entity("ServerDataAggregation.Persistence.Models.ServerStatus", b =>
                {
                    b.Property<int>("ServerStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("server_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerStatusId"));

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<string>("Modification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification");

                    b.Property<string>("Players")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("players");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    b.Property<string>("ServerSettings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_settings");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("ServerStatusId");

                    b.HasIndex("ServerId");

                    b.ToTable("server_status");
                });

            modelBuilder.Entity("ServerDataAggregation.Persistence.Models.ServerStatus", b =>
                {
                    b.HasOne("ServerDataAggregation.Persistence.Models.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });
#pragma warning restore 612, 618
        }
    }
}
